spring:
  datasource:
    password: admin
    url: jdbc:postgresql://localhost:5432/academia
    username: postgres
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
     hibernate.format_sql: true
